config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  devise_scope :user do  
     get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  get 'pages/about'
  get 'pages/courses'
  get 'pages/events'
  get 'pages/dasboard'
  get 'pages/contact'
  get 'pages/teachers'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin # only allow admin users to access Rails Admin
      can :manage, :dashboard # allow access to dashboard
    end
    return unless user.supervisor_role?

    can :manage, User
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home; end

  def about; end

  def courses; end

  def events; end

  def dasboard; end

  def contact; end

  def teachers; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Univse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/header" %>
    <%= yield %>
  
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<section id="page-banner" class="pt-105 pb-110 bg_cover" data-overlay="8" style="background-image:url(<%= image_url('page-banner-1.jpg')%>)" >
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-banner-cont">
                <h2>Universit&eacute; en ligne du Sud-Est</h2>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/"><i class="bi bi-house-fill"></i></a></li>
                        <li class="breadcrumb-item active" aria-current="page">Presentation </li>
                    </ol>
                </nav>
            </div>  <!-- page banner cont -->
        </div>
    </div> <!-- row -->
</div> <!-- container -->
</section>



<section id="about-page" class="pt-70 pb-110">
<div class="container">
    <div class="row">
        <div class="col-lg-5">
            <div class="section-title mt-50">
                <h5>A propos de nous</h5>
                <h2>Bienvenue a UNIVSE </h2>
            </div> <!-- section title -->
            <div class="about-cont">
                <p>Lorem ipsum gravida nibh vel velit auctor aliquetn sollicitudirem quibibendum auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet . Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt  mauris. <br> <br> auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet . Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt  mauris</p>
            </div>
        </div> <!-- about cont -->
        <div class="col-lg-7">
            <div class="about-image mt-50">
                <%= image_tag("about/about-2.jpg", alt: "About") %>
            </div>  <!-- about imag -->
        </div> 
    </div> <!-- row -->
    <div class="about-items pt-60">
        <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 col-sm-10">
                <div class="about-singel-items mt-30">
                    <span>01</span>
                    <h4>Pourquoi nous choisir</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sit amet nisl tempor, ultrices mi eu, maximus enim. Ut tristique. </p>
                </div> <!-- about singel -->
            </div>
            <div class="col-lg-4 col-md-6 col-sm-10">
                <div class="about-singel-items mt-30">
                    <span>02</span>
                    <h4>Notre mission</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sit amet nisl tempor, ultrices mi eu, maximus enim. Ut tristique. </p>
                </div> <!-- about singel -->
            </div>
            <div class="col-lg-4 col-md-6 col-sm-10">
                <div class="about-singel-items mt-30">
                    <span>03</span>
                    <h4>Notre vision</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sit amet nisl tempor, ultrices mi eu, maximus enim. Ut tristique. </p>
                </div> <!-- about singel -->
            </div>
        </div> <!-- row -->
    </div> <!-- about items -->
</div> <!-- container -->
</section>


<div id="counter-part" class="bg_cover pt-65 pb-110" data-overlay="8" style="background-image:url(<%= image_url('bg-2.jpg') %>)" >
<div class="container">
    <div class="row">
        <div class="col-lg-3 col-sm-6">
            <div class="singel-counter text-center mt-40">
                <span><span class="counter">30,000</span>+</span>
                <p>Nos etudiants</p>
            </div> <!-- singel counter -->
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="singel-counter text-center mt-40">
                <span><span class="counter">41,000</span>+</span>
                <p>Cours en ligne</p>
            </div> <!-- singel counter -->
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="singel-counter text-center mt-40">
                <span><span class="counter">11,000</span>+</span>
                <p>Nos diplom&acute;s</p>
            </div> <!-- singel counter -->
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="singel-counter text-center mt-40">
                <span><span class="counter">39,000</span>+</span>
                <p>Nos professeurs</p>
            </div> <!-- singel counter -->
        </div>
    </div> <!-- row -->
</div> <!-- container -->
</div>

<!--====== COUNTER PART ENDS ======-->

<!--====== TEACHERS PART START ======-->

<section id="teachers-part" class="pt-65 pb-120">
<div class="container">
    <div class="row">
        <div class="col-lg-5">
            <div class="section-title mt-50 pb-35">
                <h5>Corps professoral</h5>
                <h2>Decouvrez les</h2>
            </div> <!-- section title -->
        </div>
    </div> <!-- row -->
    <div class="row">
        <div class="col-lg-3 col-sm-6">
            <div class="singel-teachers mt-30 text-center">
                <div class="image">
                    <%= image_tag("teachers/t-1.jpg" , alt: "Teachers") %>
                </div>
                <div class="cont">
                    <a href="/pages/teachers"><h6>Suetonius Tranquillus</h6></a>
                    <span>Vice doyen</span>
                </div>
            </div> <!-- singel teachers -->
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="singel-teachers mt-30 text-center">
                <div class="image">
                    <%= image_tag("teachers/t-2.jpg" , alt: "Teachers") %>
                </div>
                <div class="cont">
                    <a href="/pages/teachers"><h6>Suetonius Tranquillus</h6></a>
                    <span>Vice doyen</span>
                </div>
            </div> <!-- singel teachers -->
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="singel-teachers mt-30 text-center">
                <div class="image">
                    <%= image_tag("teachers/t-3.jpg" , alt: "Teachers") %>
                </div>
                <div class="cont">
                    <a href="/pages/teachers"><h6>Suetonius Tranquillus</h6></a>
                    <span>Vice doyen</span>
                </div>
            </div> <!-- singel teachers -->
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="singel-teachers mt-30 text-center">
                <div class="image">
                    <%= image_tag("teachers/t-4.jpg" , alt: "Teachers") %>
                </div>
                <div class="cont">
                    <a href="/pages/teachers"><h6>Suetonius Tranquillus</h6></a>
                    <span>Vice doyen</span>
                </div>
            </div> <!-- singel teachers -->
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="singel-teachers mt-30 text-center">
                <div class="image">
                    <%= image_tag("teachers/t-5.jpg" , alt: "Teachers") %>
                </div>
                <div class="cont">
                    <a href="/pages/teachers"><h6>Suetonius Tranquillus</h6></a>
                    <span>Vice doyen</span>
                </div>
            </div> <!-- singel teachers -->
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="singel-teachers mt-30 text-center">
                <div class="image">
                    <%= image_tag("teachers/t-6.jpg" , alt: "Teachers") %>
                </div>
                <div class="cont">
                    <a href="/pages/teachers"><h6>Suetonius Tranquillus</h6></a>
                    <span>Vice doyen</span>
                </div>
            </div> <!-- singel teachers -->
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="singel-teachers mt-30 text-center">
                <div class="image">
                    <%= image_tag("teachers/t-7.jpg" , alt: "Teachers") %>
                </div>
                <div class="cont">
                    <a href="/pages/teachers"><h6>Suetonius Tranquillus</h6></a>
                    <span>Vice doyen</span>
                </div>
            </div> <!-- singel teachers -->
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="singel-teachers mt-30 text-center">
                <div class="image">
                    <%= image_tag("teachers/t-8.jpg" , alt: "Teachers") %>
                </div>
                <div class="cont">
                    <a href="/pages/teachers"><h6>Suetonius Tranquillus</h6></a>
                    <span>Vice doyen</span>
                </div>
            </div> <!-- singel teachers -->
        </div>
    </div> <!-- row -->
</div> <!-- container -->
</section>



<section id="testimonial" class="bg_cover pt-115 pb-120" data-overlay="8" style="background-image:url(<%= image_url('bg-2.jpg') %>)" >
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <div class="section-title pb-40">
                <h5>Des &eacute;tudiants</h5>
                <h2>satisfaits</h2>
            </div> <!-- section title -->
        </div>
    </div> <!-- row -->
    <div class="row testimonial-slied mt-40">
        <div class="col-lg-6">
            <div class="singel-testimonial">
                <div class="testimonial-thum">
                    <%= image_tag("testimonial/t-1.jpg" , alt: "Testimonial") %>
                    <div class="quote">
                        <i class="bi bi-quote"></i>
                    </div>
                </div>
                <div class="testimonial-cont">
                    <p>Aliquetn sollicitudirem quibibendum auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet sem nibh id elit sollicitudirem </p>
                    <h6>Octavia Minor</h6>
                    <span>Lic. Sces Informatiques</span>
                </div>
            </div> <!-- singel testimonial -->
        </div>
        <div class="col-lg-6">
            <div class="singel-testimonial">
                <div class="testimonial-thum">
                    <%= image_tag("testimonial/t-2.jpg" , alt: "Testimonial") %>
                    <div class="quote">
                        <i class="bi bi-quote"></i>
                    </div>
                </div>
                <div class="testimonial-cont">
                    <p>Aliquetn sollicitudirem quibibendum auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet sem nibh id elit sollicitudirem </p>
                    <h6>Octavia Minor</h6>
                    <span>Lic. Sces Informatiques</span>
                </div>
            </div> <!-- singel testimonial -->
        </div>
        <div class="col-lg-6">
            <div class="singel-testimonial">
                <div class="testimonial-thum">
                    <%= image_tag("testimonial/t-3.jpg" , alt: "Testimonial") %>
                    <div class="quote">
                        <i class="bi bi-quote"></i>
                    </div>
                </div>
                <div class="testimonial-cont">
                    <p>Aliquetn sollicitudirem quibibendum auci elit cons equat ipsutis sem nibh id elit. Duis sed odio sit amet sem nibh id elit sollicitudirem </p>
                    <h6>Junia Lepida</h6>
                    <span>Lic. Sces Informatiques</span>
                </div>
            </div> <!-- singel testimonial -->
        </div>
    </div> <!-- testimonial slied -->
</div> <!-- container -->
</section>



<div id="patnar-logo" class="pt-40 pb-80 gray-bg">
<div class="container">
    <div class="row patnar-slied">
        <div class="col-lg-12">
            <div class="singel-patnar text-center mt-40">
                <%= image_tag("patnar-logo/p-1.png" , alt: "Logo") %>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="singel-patnar text-center mt-40">
                <%= image_tag("patnar-logo/p-2.png" , alt: "Logo") %>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="singel-patnar text-center mt-40">
                <%= image_tag("patnar-logo/p-3.png" , alt: "Logo") %>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="singel-patnar text-center mt-40">
                <%= image_tag("patnar-logo/p-4.png" , alt: "Logo") %>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="singel-patnar text-center mt-40">
                <%= image_tag("patnar-logo/p-2.png" , alt: "Logo") %>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="singel-patnar text-center mt-40">
                <%= image_tag("patnar-logo/p-3.png" , alt: "Logo") %>
            </div>
        </div>
    </div> <!-- row -->
</div> <!-- container -->
</div> 

app/views/pages/contact.html.erb
<section id="page-banner" class="pt-105 pb-130 bg_cover" data-overlay="8" style="background-image:url(<%= image_url('page-banner-6.jpg')%>)" >
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="page-banner-cont">
                        <h2>Contact</h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/"><i class="bi bi-house-fill"></i></a></li>
                                <li class="breadcrumb-item active" aria-current="page">Contact</li>
                            </ol>
                        </nav>
                    </div>  <!-- page banner cont -->
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
    </section>
    
   
    <section id="contact-page" class="pt-90 pb-120 gray-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-7">
                    <div class="contact-from mt-30">
                        <div class="section-title">
                            <h5>Contactez nous</h5>
                            <h2>Laisser nous un message</h2>
                        </div> <!-- section title -->
                        <div class="main-form pt-45">
                            <form id="contact-form" action="#" method="post" data-bs-toggle="validator">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="singel-form form-group">
                                            <input name="name" type="text" placeholder="Nom complet" data-bs-error="Veuillez entrer votre nom." required="required">
                                            <div class="help-block with-errors"></div>
                                        </div> <!-- singel form -->
                                    </div>
                                    <div class="col-md-6">
                                        <div class="singel-form form-group">
                                            <input name="email" type="email" placeholder="Email" data-bs-error="Veuillez entrer votre courriel." required="required">
                                            <div class="help-block with-errors"></div>
                                        </div> <!-- singel form -->
                                    </div>
                                    <div class="col-md-6">
                                        <div class="singel-form form-group">
                                            <input name="subject" type="text" placeholder="Objet" data-bs-error="Objet est obligatoire." required="required">
                                            <div class="help-block with-errors"></div>
                                        </div> <!-- singel form --> 
                                    </div>
                                    <div class="col-md-6">
                                        <div class="singel-form form-group">
                                            <input name="phone" type="text" placeholder="Phone" data-bs-error="Votre numero de telephone est obligatoire." required="required">
                                            <div class="help-block with-errors"></div>
                                        </div> <!-- singel form -->
                                    </div>
                                    <div class="col-md-12">
                                        <div class="singel-form form-group">
                                            <textarea name="messege" placeholder="Message" data-bs-error="Veuillez entrer votre message." required="required"></textarea>
                                            <div class="help-block with-errors"></div>
                                        </div> <!-- singel form -->
                                    </div>
                                    <p class="form-message"></p>
                                    <div class="col-md-12">
                                        <div class="singel-form">
                                            <button type="submit" class="main-btn">Envoyez</button>
                                        </div> <!-- singel form -->
                                    </div> 
                                </div> <!-- row -->
                            </form>
                        </div> <!-- main form -->
                    </div> <!--  contact from -->
                </div>
                <div class="col-lg-5">
                    <div class="contact-address mt-30">
                        <ul>
                            <li>
                                <div class="singel-address">
                                    <div class="icon">
                                        <i class="bi bi-house-fill"></i>
                                    </div>
                                    <div class="cont">
                                        <p>27, Avenue Baranquilla, Jacmel</p>
                                    </div>
                                </div> <!-- singel address -->
                            </li>
                            <li>
                                <div class="singel-address">
                                    <div class="icon">
                                        <i class="bi bi-telephone"></i>
                                    </div>
                                    <div class="cont">
                                        <p>+(509) 8888-8888</p>
                                        <p>+(509) 8888-8888</p>
                                    </div>
                                </div> <!-- singel address -->
                            </li>
                            <li>
                                <div class="singel-address">
                                    <div class="icon">
                                        <i class="bi bi-envelope-at-fill"></i>
                                    </div>
                                    <div class="cont">
                                        <p>info@univse.edu</p>
                                        <p>admission@univse.edu</p>
                                    </div>
                                </div> <!-- singel address -->
                            </li>
                        </ul>
                    </div> <!-- contact address -->
                    <div class="map mt-30">
                        <div id="contact-map"></div>
                    </div> <!-- map -->
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
    </section>
    

app/views/pages/dasboard.html.erb
<section id="page-banner" class="pt-105 pb-110 bg_cover" data-overlay="8" style="background-image: url(images/page-banner-2.jpg)">
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-banner-cont">
                <h2>Cours</h2>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/"><i class="bi bi-house-fill"></i></a></li>
                        <li class="breadcrumb-item active" aria-current="page">Tableau de bord</li>
                    </ol>
                </nav>
            </div>  <!-- page banner cont -->
        </div>
    </div> <!-- row -->
</div> <!-- container -->
</section>

app/views/shared/_header.html.erb
<header id="header-part">
       
<div class="header-top d-none d-md-block">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-8">
                <div class="header-contact text-lg-left text-center">
                    <ul>
                        <li><%= image_tag("all-icon/call.png", alt: "icon") %><span>+(509) 8888-8888</span></li>
                        <li><%= image_tag("all-icon/email.png", alt: "icon") %><span>info@univse.edu</span></li>
                        <li><%= image_tag("all-icon/map.png", alt: "icon") %><span>127/5 Jacmel, Haiti</span></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="header-social text-lg-right text-center">
                    <ul>
                        <li><a href="#"><i class="bi bi-facebook"></i></a></li>
                        <li><a href="#"><i class="bi bi-twitter"></i></a></li>
                        <li><a href="#"><i class="bi bi-instagram"></i></a></li>
                        <li><a href="#"><i class="bi bi-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>
        </div> <!-- row -->
    </div> <!-- container -->
</div> <!-- header top -->

<div class="navigation navigation-2">
    <div class="container">
        <div class="row no-gutters">
            <div class="col-lg-11 col-md-10 col-sm-9 col-9">
                <nav class="navbar navbar-expand-lg">
                    <a class="navbar-brand" href="index-3.html">
                        <%= image_tag("logo.png", alt: "Logo") %>
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <%= link_to "UNIVSE", root_path,  class:"active" %>

                            </li>
                            <li class="nav-item">
                                <%= link_to "Presentation" , pages_about_path %>
                            </li>
                            <li class="nav-item">
                                <%= link_to "Formations" , pages_courses_path %>

                            </li>
                            <% if user_signed_in? %>
                            <li class="nav-item">
                                <%= link_to "Evenements", pages_events_path %>

                            </li>
                            <% end %>
                            <li class="nav-item">
                                <%= link_to "Dashboard", pages_dasboard_path %>
                            </li>

 
                            <li class="nav-item">
                                <%= link_to "Contact", pages_contact_path %>

                            </li>
                        </ul>
                    </div>
                </nav> <!-- nav -->
            </div>
            <div class="col-lg-1 col-md-2 col-sm-3 col-3">
                <div class="right-icon text-right">
                    <ul>
                        <li><a href="#" id="search"><i class="bi bi-search"></i></a></li>
                        <li class="dropdown" ><i class="bi bi-person-circle"></i>
  <div class="dropdown-options">
<% if user_signed_in? %>

  <%= link_to('Edit registration', edit_user_registration_path) %>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-default btn-sm" %>        

<% else %>

  <%= link_to('Register', new_user_registration_path)  %>
  <%= link_to('Login', new_user_session_path)  %>  

<% end %>
  </div>
                        </li>

                    </ul>

                </div> <!-- right icon -->
            </div>
        </div> <!-- row -->
    </div> <!-- container -->
</div>

</header>

<!--====== HEADER PART ENDS ======-->

<!--====== SEARCH BOX PART START ======-->

<div class="search-box">
<div class="serach-form">
    <div class="closebtn">
        <span></span>
        <span></span>
    </div>
    <form action="#">
        <input type="text" placeholder="Search by keyword">
        <button><i class="fa fa-search"></i></button>
    </form>
</div> <!-- serach form -->
</div>